name: rubocop-challenge-docker
description: Internal implementation for r7kamura/rubocop-challenge.
inputs:
  base_branch:
    description: Pull request base branch.
    required: true
  github_token:
    description: GitHub access token.
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.base_branch }}
    - ${{ inputs.github_token }}
branding:
  color: red
  icon: git-pull-request
